In [135]:
!pip install snowflake-connector-python

Requirement already satisfied: snowflake-connector-python in c:\users\gauta\anaconda3\lib\site-packages (3.3.1)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (1.5.1)
Requirement already satisfied: cffi<2.0.0,>=1.9 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (1.15.1)
Requirement already satisfied: cryptography<42.0.0,>=3.1.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (41.0.3)
Requirement already satisfied: oscrypto<2.0.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (1.3.0)
Requirement already satisfied: pyOpenSSL<24.0.0,>=16.2.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (23.2.0)
Requirement already satisfied: pycryptodomex!=3.5.0,<4.0.0,>=3.2 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (3.19.0)
Requirement already satisfied: pyjwt<3.0.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (2.4.0)
Requirement already satisfied: pytz in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (2023.3.post1)
Requirement already satisfied: requests<3.0.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (2.31.0)
Requirement already satisfied: packaging in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (23.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (2023.7.22)
Requirement already satisfied: typing-extensions<5,>=4.3 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (4.7.1)
Requirement already satisfied: filelock<4,>=3.5 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (3.9.0)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (2.4.0)
Requirement already satisfied: platformdirs<4.0.0,>=2.6.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (3.10.0)
Requirement already satisfied: tomlkit in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python) (0.11.1)
Requirement already satisfied: pycparser in c:\users\gauta\anaconda3\lib\site-packages (from cffi<2.0.0,>=1.9->snowflake-connector-python) (2.21)

In [136]:
!pip install "snowflake-connector-python[pandas]"

Requirement already satisfied: snowflake-connector-python[pandas] in c:\users\gauta\anaconda3\lib\site-packages (3.3.1)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (1.5.1)
Requirement already satisfied: cffi<2.0.0,>=1.9 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (1.15.1)
Requirement already satisfied: cryptography<42.0.0,>=3.1.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (41.0.3)
Requirement already satisfied: oscrypto<2.0.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (1.3.0)
Requirement already satisfied: pyOpenSSL<24.0.0,>=16.2.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (23.2.0)
Requirement already satisfied: pycryptodomex!=3.5.0,<4.0.0,>=3.2 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (3.19.0)
Requirement already satisfied: pyjwt<3.0.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (2.4.0)
Requirement already satisfied: pytz in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (2023.3.post1)
Requirement already satisfied: requests<3.0.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (2.31.0)
Requirement already satisfied: packaging in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (23.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (2023.7.22)
Requirement already satisfied: typing-extensions<5,>=4.3 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (4.7.1)
Requirement already satisfied: filelock<4,>=3.5 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (3.9.0)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (2.4.0)
Requirement already satisfied: platformdirs<4.0.0,>=2.6.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (3.10.0)
Requirement already satisfied: tomlkit in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (0.11.1)
Requirement already satisfied: pandas<2.1.0,>=1.0.0 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (2.0.3)
Requirement already satisfied: pyarrow<10.1.0,>=10.0.1 in c:\users\gauta\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (10.0.1)
Requirement already satisfied: pycparser in c:\users\gauta\anaconda3\lib\site-packages (from cffi<2.0.0,>=1.9->snowflake-connector-python[pandas]) (2.21)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gauta\anaconda3\lib\site-packages (from pandas<2.1.0,>=1.0.0->snowflake-connector-python[pandas]) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\gauta\anaconda3\lib\site-packages (from pandas<2.1.0,>=1.0.0->snowflake-connector-python[pandas]) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\gauta\anaconda3\lib\site-packages (from pandas<2.1.0,>=1.0.0->snowflake-connector-python[pandas]) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\gauta\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<2.1.0,>=1.0.0->snowflake-connector-python[pandas]) (1.16.0)

In [197]:
!jupyter nbextension install --py luxwidget
!jupyter nbextension enable --py luxwidget

Installing C:\Users\gauta\anaconda3\Lib\site-packages\luxwidget\nbextension/static -> luxwidget
Making directory: C:\ProgramData\jupyter\nbextensions\luxwidget\
Copying: C:\Users\gauta\anaconda3\Lib\site-packages\luxwidget\nbextension\static\extension.js -> C:\ProgramData\jupyter\nbextensions\luxwidget\extension.js
Copying: C:\Users\gauta\anaconda3\Lib\site-packages\luxwidget\nbextension\static\index.js -> C:\ProgramData\jupyter\nbextensions\luxwidget\index.js
Copying: C:\Users\gauta\anaconda3\Lib\site-packages\luxwidget\nbextension\static\index.js.map -> C:\ProgramData\jupyter\nbextensions\luxwidget\index.js.map
- Validating: ok

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable luxwidget --py

Enabling notebook extension luxwidget/extension...
      - Validating: ok

In [13]:
# Adding a toggle between Lux and Pandas
!pip install lux-api

Requirement already satisfied: lux-api in c:\users\gauta\anaconda3\lib\site-packages (0.5.1)
Requirement already satisfied: scipy>=1.3.3 in c:\users\gauta\anaconda3\lib\site-packages (from lux-api) (1.11.1)
Requirement already satisfied: altair>=4.0.0 in c:\users\gauta\anaconda3\lib\site-packages (from lux-api) (5.1.2)
Requirement already satisfied: numpy>=1.16.5 in c:\users\gauta\anaconda3\lib\site-packages (from lux-api) (1.24.3)
Requirement already satisfied: pandas in c:\users\gauta\anaconda3\lib\site-packages (from lux-api) (2.0.3)
Requirement already satisfied: scikit-learn>=0.22 in c:\users\gauta\anaconda3\lib\site-packages (from lux-api) (1.3.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\gauta\anaconda3\lib\site-packages (from lux-api) (3.7.2)
Requirement already satisfied: lux-widget>=0.1.4 in c:\users\gauta\anaconda3\lib\site-packages (from lux-api) (0.1.11)
Requirement already satisfied: autopep8>=1.5 in c:\users\gauta\anaconda3\lib\site-packages (from lux-api) (1.6.0)
Requirement already satisfied: iso3166 in c:\users\gauta\anaconda3\lib\site-packages (from lux-api) (2.1.1)
Requirement already satisfied: psutil>=5.9.0 in c:\users\gauta\anaconda3\lib\site-packages (from lux-api) (5.9.0)
Requirement already satisfied: sh in c:\users\gauta\anaconda3\lib\site-packages (from lux-api) (2.0.6)
Requirement already satisfied: jinja2 in c:\users\gauta\anaconda3\lib\site-packages (from altair>=4.0.0->lux-api) (3.1.2)
Requirement already satisfied: jsonschema>=3.0 in c:\users\gauta\anaconda3\lib\site-packages (from altair>=4.0.0->lux-api) (4.17.3)
Requirement already satisfied: packaging in c:\users\gauta\anaconda3\lib\site-packages (from altair>=4.0.0->lux-api) (23.1)
Requirement already satisfied: toolz in c:\users\gauta\anaconda3\lib\site-packages (from altair>=4.0.0->lux-api) (0.12.0)
Requirement already satisfied: pycodestyle>=2.8.0 in c:\users\gauta\anaconda3\lib\site-packages (from autopep8>=1.5->lux-api) (2.10.0)
Requirement already satisfied: toml in c:\users\gauta\anaconda3\lib\site-packages (from autopep8>=1.5->lux-api) (0.10.2)
Requirement already satisfied: notebook>=4.0.0 in c:\users\gauta\anaconda3\lib\site-packages (from lux-widget>=0.1.4->lux-api) (6.5.4)
Requirement already satisfied: ipywidgets>=7.5.0 in c:\users\gauta\anaconda3\lib\site-packages (from lux-widget>=0.1.4->lux-api) (8.0.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\gauta\anaconda3\lib\site-packages (from matplotlib>=3.0.0->lux-api) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\users\gauta\anaconda3\lib\site-packages (from matplotlib>=3.0.0->lux-api) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\gauta\anaconda3\lib\site-packages (from matplotlib>=3.0.0->lux-api) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\gauta\anaconda3\lib\site-packages (from matplotlib>=3.0.0->lux-api) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in c:\users\gauta\anaconda3\lib\site-packages (from matplotlib>=3.0.0->lux-api) (9.4.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\gauta\anaconda3\lib\site-packages (from matplotlib>=3.0.0->lux-api) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\gauta\anaconda3\lib\site-packages (from matplotlib>=3.0.0->lux-api) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\gauta\anaconda3\lib\site-packages (from pandas->lux-api) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\gauta\anaconda3\lib\site-packages (from pandas->lux-api) (2023.3)
Requirement already satisfied: joblib>=1.1.1 in c:\users\gauta\anaconda3\lib\site-packages (from scikit-learn>=0.22->lux-api) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\gauta\anaconda3\lib\site-packages (from scikit-learn>=0.22->lux-api) (2.2.0)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\gauta\anaconda3\lib\site-packages (from ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (6.25.0)
Requirement already satisfied: ipython>=6.1.0 in c:\users\gauta\anaconda3\lib\site-packages (from ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (8.15.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\gauta\anaconda3\lib\site-packages (from ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (5.7.1)
Requirement already satisfied: widgetsnbextension~=4.0 in c:\users\gauta\anaconda3\lib\site-packages (from ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (4.0.5)
Requirement already satisfied: jupyterlab-widgets~=3.0 in c:\users\gauta\anaconda3\lib\site-packages (from ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (3.0.5)
Requirement already satisfied: attrs>=17.4.0 in c:\users\gauta\anaconda3\lib\site-packages (from jsonschema>=3.0->altair>=4.0.0->lux-api) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\gauta\anaconda3\lib\site-packages (from jsonschema>=3.0->altair>=4.0.0->lux-api) (0.18.0)
Requirement already satisfied: tornado>=6.1 in c:\users\gauta\anaconda3\lib\site-packages (from notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (6.3.2)
Requirement already satisfied: pyzmq>=17 in c:\users\gauta\anaconda3\lib\site-packages (from notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (23.2.0)
Requirement already satisfied: argon2-cffi in c:\users\gauta\anaconda3\lib\site-packages (from notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (21.3.0)
Requirement already satisfied: jupyter-core>=4.6.1 in c:\users\gauta\anaconda3\lib\site-packages (from notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (5.3.0)
Requirement already satisfied: jupyter-client>=5.3.4 in c:\users\gauta\anaconda3\lib\site-packages (from notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (7.4.9)
Requirement already satisfied: ipython-genutils in c:\users\gauta\anaconda3\lib\site-packages (from notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (0.2.0)
Requirement already satisfied: nbformat in c:\users\gauta\anaconda3\lib\site-packages (from notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (5.9.2)
Requirement already satisfied: nbconvert>=5 in c:\users\gauta\anaconda3\lib\site-packages (from notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (6.5.4)
Requirement already satisfied: nest-asyncio>=1.5 in c:\users\gauta\anaconda3\lib\site-packages (from notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (1.5.6)
Requirement already satisfied: Send2Trash>=1.8.0 in c:\users\gauta\anaconda3\lib\site-packages (from notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (1.8.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\gauta\anaconda3\lib\site-packages (from notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (0.17.1)
Requirement already satisfied: prometheus-client in c:\users\gauta\anaconda3\lib\site-packages (from notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (0.14.1)
Requirement already satisfied: nbclassic>=0.4.7 in c:\users\gauta\anaconda3\lib\site-packages (from notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (0.5.5)
Requirement already satisfied: six>=1.5 in c:\users\gauta\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->lux-api) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\gauta\anaconda3\lib\site-packages (from jinja2->altair>=4.0.0->lux-api) (2.1.1)
Requirement already satisfied: comm>=0.1.1 in c:\users\gauta\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (0.1.2)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\gauta\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (1.6.7)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\gauta\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (0.1.6)
Requirement already satisfied: backcall in c:\users\gauta\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (0.2.0)
Requirement already satisfied: decorator in c:\users\gauta\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\gauta\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (0.18.1)
Requirement already satisfied: pickleshare in c:\users\gauta\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\users\gauta\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (3.0.36)
Requirement already satisfied: pygments>=2.4.0 in c:\users\gauta\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (2.15.1)
Requirement already satisfied: stack-data in c:\users\gauta\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (0.2.0)
Requirement already satisfied: colorama in c:\users\gauta\anaconda3\lib\site-packages (from ipython>=6.1.0->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (0.4.6)
Requirement already satisfied: entrypoints in c:\users\gauta\anaconda3\lib\site-packages (from jupyter-client>=5.3.4->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (0.4)
Requirement already satisfied: platformdirs>=2.5 in c:\users\gauta\anaconda3\lib\site-packages (from jupyter-core>=4.6.1->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\gauta\anaconda3\lib\site-packages (from jupyter-core>=4.6.1->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (305.1)
Requirement already satisfied: jupyter-server>=1.8 in c:\users\gauta\anaconda3\lib\site-packages (from nbclassic>=0.4.7->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (1.23.4)
Requirement already satisfied: notebook-shim>=0.1.0 in c:\users\gauta\anaconda3\lib\site-packages (from nbclassic>=0.4.7->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (0.2.2)
Requirement already satisfied: lxml in c:\users\gauta\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (4.9.3)
Requirement already satisfied: beautifulsoup4 in c:\users\gauta\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (4.12.2)
Requirement already satisfied: bleach in c:\users\gauta\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (4.1.0)
Requirement already satisfied: defusedxml in c:\users\gauta\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\gauta\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (0.1.2)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\gauta\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (0.8.4)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\gauta\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (0.5.13)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\gauta\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (1.5.0)
Requirement already satisfied: tinycss2 in c:\users\gauta\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (1.2.1)
Requirement already satisfied: fastjsonschema in c:\users\gauta\anaconda3\lib\site-packages (from nbformat->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (2.16.2)
Requirement already satisfied: pywinpty>=1.1.0 in c:\users\gauta\anaconda3\lib\site-packages (from terminado>=0.8.3->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (2.0.10)
Requirement already satisfied: argon2-cffi-bindings in c:\users\gauta\anaconda3\lib\site-packages (from argon2-cffi->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (21.2.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\gauta\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (0.8.3)
Requirement already satisfied: anyio<4,>=3.1.0 in c:\users\gauta\anaconda3\lib\site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (3.5.0)
Requirement already satisfied: websocket-client in c:\users\gauta\anaconda3\lib\site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (0.58.0)
Requirement already satisfied: wcwidth in c:\users\gauta\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=6.1.0->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (0.2.5)
Requirement already satisfied: cffi>=1.0.1 in c:\users\gauta\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (1.15.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\gauta\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (2.4)
Requirement already satisfied: webencodings in c:\users\gauta\anaconda3\lib\site-packages (from bleach->nbconvert>=5->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (0.5.1)
Requirement already satisfied: executing in c:\users\gauta\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (0.8.3)
Requirement already satisfied: asttokens in c:\users\gauta\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\gauta\anaconda3\lib\site-packages (from stack-data->ipython>=6.1.0->ipywidgets>=7.5.0->lux-widget>=0.1.4->lux-api) (0.2.2)
Requirement already satisfied: idna>=2.8 in c:\users\gauta\anaconda3\lib\site-packages (from anyio<4,>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (3.4)
Requirement already satisfied: sniffio>=1.1 in c:\users\gauta\anaconda3\lib\site-packages (from anyio<4,>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (1.2.0)
Requirement already satisfied: pycparser in c:\users\gauta\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.0.0->lux-widget>=0.1.4->lux-api) (2.21)

In [32]:
import pandas as pd
import os
import snowflake.connector
import numpy as np

In [8]:
#import lux

### Snowflake connection with Juypter notebook

In [40]:
#Set snowflake connection parameters

conn=snowflake.connector.connect(
        user='UNT_TEAM19',
        password='@Fall2022',
        account='aa-itor_universities',
        warehouse='UNIVERSITY_READER',
        database='LOCAL_DATABASE',
        schema='ORAAUE',
        role='UNT_STUDENT'
    )

#Cursor
cur=conn.cursor()

### Load data into dataframe

In [10]:
#SQL Query
query = """
SELECT *
FROM LOCAL_DATABASE.ORAAUE.UNT_BAGS;
"""
cur.execute(query)

In [11]:
#Fetch all the rows from cursor
results=cur.fetchall()

In [12]:
#Column headers
column_names = [desc[0] for desc in cur.description]

In [13]:
#Store database into pandas dataframe
df=pd.DataFrame(results, columns=column_names)

In [14]:
df

C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:567: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:548: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:548: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:567: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:548: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:567: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\IPython\core\formatters.py:922: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
Please report the following issue on Github: https://github.com/lux-org/lux/issues

C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py:632: UserWarning:Traceback (most recent call last):
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py", line 594, in _ipython_display_
    self.maintain_recs()
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py", line 436, in maintain_recs
    custom_action_collection = custom_actions(rec_df)
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\action\custom.py", line 76, in custom_actions
    recommendation = lux.config.actions[action_name].action(ldf)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\action\correlation.py", line 50, in correlation
    vlist = VisList(intent, ldf)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\vis\VisList.py", line 43, in __init__
    self.refresh_source(self._source)
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\vis\VisList.py", line 336, in refresh_source
    lux.config.executor.execute(self._collection, ldf, approx=approx)
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py", line 147, in execute
    PandasExecutor.execute_2D_binning(vis)
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py", line 413, in execute_2D_binning
    vis._vis_data["xBin"] = pd.cut(vis._vis_data[x_attr], bins=lux.config.heatmap_bin_size)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\reshape\tile.py", line 259, in cut
    mn, mx = (mi + 0.0 for mi in rng)
    ^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\reshape\tile.py", line 259, in <genexpr>
    mn, mx = (mi + 0.0 for mi in rng)
              ~~~^~~~~
TypeError: can only concatenate str (not "float") to str

,FLIGHTNUMBER,STATION,DESTINATION,SCHD_LEG_DEP_TMS,ACTL_LEG_DEP_TMS,INTERNATIONAL,FLEETTYPE,BODYTYPE,BR_ARVL_TMS,COUNT_BAGS,SF_LOAD_TMS
0,2765,ORD,PHX,2023-06-06 13:42:00,2023-06-06 15:00:00,0,321,NARROWBODY,2023-06-06 11:43:00,1,2023-09-26 17:04:53.493
1,527,ORD,LGA,2023-08-11 10:25:00,2023-08-11 10:27:00,0,737,NARROWBODY,2023-08-11 08:16:00,1,2023-09-26 17:04:53.493
2,492,ORD,CUN,2023-06-27 10:12:00,2023-06-27 10:16:00,1,737,NARROWBODY,2023-06-27 09:16:00,1,2023-09-26 17:04:53.493
3,282,ORD,MBJ,2023-06-18 08:43:00,2023-06-18 08:39:00,1,737,NARROWBODY,2023-06-18 07:30:00,1,2023-09-26 17:04:53.493
4,1106,ORD,DFW,2023-08-10 10:56:00,2023-08-10 11:09:00,0,737,NARROWBODY,2023-08-10 09:27:00,1,2023-09-26 17:04:53.493
...,...,...,...,...,...,...,...,...,...,...,...
6661554,957,MIA,SCL,2023-05-27 23:25:00,2023-05-27 23:18:00,1,787,WIDEBODY,2023-05-27 18:57:00,5,2023-09-26 17:04:53.493
6661555,556,MIA,ORD,2023-07-03 08:39:00,2023-07-03 08:31:00,0,737,NARROWBODY,2023-07-03 05:51:00,1,2023-09-26 17:04:53.493
6661556,1566,MIA,RDU,2023-05-30 20:23:00,2023-05-30 21:31:00,0,737,NARROWBODY,2023-05-30 15:11:00,2,2023-09-26 17:04:53.493
6661557,1006,MIA,ATL,2023-08-27 19:49:00,2023-08-27 20:56:00,0,321,NARROWBODY,2023-08-27 18:01:00,1,2023-09-26 17:04:53.493
6661558,1513,MIA,GEO,2023-06-21 18:14:00,2023-06-21 18:10:00,1,737,NARROWBODY,2023-06-21 15:59:00,2,2023-09-26 17:04:53.493

### Data transformation

In [15]:
#Split timestamp into date and time
df['SCHD_LEG_DEP_DATE'] = pd.to_datetime(df['SCHD_LEG_DEP_TMS']).dt.date
df['SCHD_LEG_DEP_TIME'] = pd.to_datetime(df['SCHD_LEG_DEP_TMS']).dt.time

In [16]:
df['ACTL_LEG_DEP_DATE'] = pd.to_datetime(df['ACTL_LEG_DEP_TMS']).dt.date
df['ACTL_LEG_DEP_TIME'] = pd.to_datetime(df['ACTL_LEG_DEP_TMS']).dt.time

In [17]:
df['BR_ARVL_DATE'] = pd.to_datetime(df['BR_ARVL_TMS']).dt.date
df['BR_ARVL_TIME'] = pd.to_datetime(df['BR_ARVL_TMS']).dt.time

In [18]:
df['SF_LOAD_DATE'] = pd.to_datetime(df['SF_LOAD_TMS']).dt.date
df['SF_LOAD_TIME'] = pd.to_datetime(df['SF_LOAD_TMS']).dt.time

In [19]:
df.head()

C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:567: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:548: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:548: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:567: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:548: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:567: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\IPython\core\formatters.py:922: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
Please report the following issue on Github: https://github.com/lux-org/lux/issues

C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py:632: UserWarning:Traceback (most recent call last):
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py", line 581, in _ipython_display_
    self.maintain_metadata()
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py", line 146, in maintain_metadata
    self.compute_metadata()
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py", line 126, in compute_metadata
    lux.config.executor.compute_dataset_metadata(self)
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py", line 448, in compute_dataset_metadata
    self.compute_data_type(ldf)
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py", line 506, in compute_data_type
    elif check_if_id_like(ldf, attr):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\utils\utils.py", line 104, in check_if_id_like
    diff = series.diff()
           ^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\series.py", line 2870, in diff
    result = algorithms.diff(self._values, periods)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\algorithms.py", line 1454, in diff
    out_arr[res_indexer] = op(arr[res_indexer], arr[lag_indexer])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for -: 'datetime.time' and 'datetime.time'

,FLIGHTNUMBER,STATION,DESTINATION,SCHD_LEG_DEP_TMS,ACTL_LEG_DEP_TMS,INTERNATIONAL,FLEETTYPE,BODYTYPE,BR_ARVL_TMS,COUNT_BAGS,SF_LOAD_TMS,SCHD_LEG_DEP_DATE,SCHD_LEG_DEP_TIME,ACTL_LEG_DEP_DATE,ACTL_LEG_DEP_TIME,BR_ARVL_DATE,BR_ARVL_TIME,SF_LOAD_DATE,SF_LOAD_TIME
0,2765,ORD,PHX,2023-06-06 13:42:00,2023-06-06 15:00:00,0,321,NARROWBODY,2023-06-06 11:43:00,1,2023-09-26 17:04:53.493,2023-06-06,13:42:00,2023-06-06,15:00:00,2023-06-06,11:43:00,2023-09-26,17:04:53.493000
1,527,ORD,LGA,2023-08-11 10:25:00,2023-08-11 10:27:00,0,737,NARROWBODY,2023-08-11 08:16:00,1,2023-09-26 17:04:53.493,2023-08-11,10:25:00,2023-08-11,10:27:00,2023-08-11,08:16:00,2023-09-26,17:04:53.493000
2,492,ORD,CUN,2023-06-27 10:12:00,2023-06-27 10:16:00,1,737,NARROWBODY,2023-06-27 09:16:00,1,2023-09-26 17:04:53.493,2023-06-27,10:12:00,2023-06-27,10:16:00,2023-06-27,09:16:00,2023-09-26,17:04:53.493000
3,282,ORD,MBJ,2023-06-18 08:43:00,2023-06-18 08:39:00,1,737,NARROWBODY,2023-06-18 07:30:00,1,2023-09-26 17:04:53.493,2023-06-18,08:43:00,2023-06-18,08:39:00,2023-06-18,07:30:00,2023-09-26,17:04:53.493000
4,1106,ORD,DFW,2023-08-10 10:56:00,2023-08-10 11:09:00,0,737,NARROWBODY,2023-08-10 09:27:00,1,2023-09-26 17:04:53.493,2023-08-10,10:56:00,2023-08-10,11:09:00,2023-08-10,09:27:00,2023-09-26,17:04:53.493000

## EDA

### Data summary

In [20]:
print("Shape of the dataset:", df.shape)

Shape of the dataset: (6661559, 19)

In [21]:
df.head()

C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:567: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:548: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:548: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:567: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:548: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:567: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\IPython\core\formatters.py:922: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
Please report the following issue on Github: https://github.com/lux-org/lux/issues

C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py:632: UserWarning:Traceback (most recent call last):
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py", line 581, in _ipython_display_
    self.maintain_metadata()
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py", line 146, in maintain_metadata
    self.compute_metadata()
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py", line 126, in compute_metadata
    lux.config.executor.compute_dataset_metadata(self)
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py", line 448, in compute_dataset_metadata
    self.compute_data_type(ldf)
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py", line 506, in compute_data_type
    elif check_if_id_like(ldf, attr):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\utils\utils.py", line 104, in check_if_id_like
    diff = series.diff()
           ^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\series.py", line 2870, in diff
    result = algorithms.diff(self._values, periods)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\algorithms.py", line 1454, in diff
    out_arr[res_indexer] = op(arr[res_indexer], arr[lag_indexer])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for -: 'datetime.time' and 'datetime.time'

,FLIGHTNUMBER,STATION,DESTINATION,SCHD_LEG_DEP_TMS,ACTL_LEG_DEP_TMS,INTERNATIONAL,FLEETTYPE,BODYTYPE,BR_ARVL_TMS,COUNT_BAGS,SF_LOAD_TMS,SCHD_LEG_DEP_DATE,SCHD_LEG_DEP_TIME,ACTL_LEG_DEP_DATE,ACTL_LEG_DEP_TIME,BR_ARVL_DATE,BR_ARVL_TIME,SF_LOAD_DATE,SF_LOAD_TIME
0,2765,ORD,PHX,2023-06-06 13:42:00,2023-06-06 15:00:00,0,321,NARROWBODY,2023-06-06 11:43:00,1,2023-09-26 17:04:53.493,2023-06-06,13:42:00,2023-06-06,15:00:00,2023-06-06,11:43:00,2023-09-26,17:04:53.493000
1,527,ORD,LGA,2023-08-11 10:25:00,2023-08-11 10:27:00,0,737,NARROWBODY,2023-08-11 08:16:00,1,2023-09-26 17:04:53.493,2023-08-11,10:25:00,2023-08-11,10:27:00,2023-08-11,08:16:00,2023-09-26,17:04:53.493000
2,492,ORD,CUN,2023-06-27 10:12:00,2023-06-27 10:16:00,1,737,NARROWBODY,2023-06-27 09:16:00,1,2023-09-26 17:04:53.493,2023-06-27,10:12:00,2023-06-27,10:16:00,2023-06-27,09:16:00,2023-09-26,17:04:53.493000
3,282,ORD,MBJ,2023-06-18 08:43:00,2023-06-18 08:39:00,1,737,NARROWBODY,2023-06-18 07:30:00,1,2023-09-26 17:04:53.493,2023-06-18,08:43:00,2023-06-18,08:39:00,2023-06-18,07:30:00,2023-09-26,17:04:53.493000
4,1106,ORD,DFW,2023-08-10 10:56:00,2023-08-10 11:09:00,0,737,NARROWBODY,2023-08-10 09:27:00,1,2023-09-26 17:04:53.493,2023-08-10,10:56:00,2023-08-10,11:09:00,2023-08-10,09:27:00,2023-09-26,17:04:53.493000

In [22]:
df.info()

<class 'lux.core.frame.LuxDataFrame'>
RangeIndex: 6661559 entries, 0 to 6661558
Data columns (total 19 columns):
 #   Column             Dtype
---  ------             -----
 0   FLIGHTNUMBER       int64
 1   STATION            object
 2   DESTINATION        object
 3   SCHD_LEG_DEP_TMS   datetime64[ns]
 4   ACTL_LEG_DEP_TMS   datetime64[ns]
 5   INTERNATIONAL      int64
 6   FLEETTYPE          object
 7   BODYTYPE           object
 8   BR_ARVL_TMS        datetime64[ns]
 9   COUNT_BAGS         int64
 10  SF_LOAD_TMS        datetime64[ns]
 11  SCHD_LEG_DEP_DATE  object
 12  SCHD_LEG_DEP_TIME  object
 13  ACTL_LEG_DEP_DATE  object
 14  ACTL_LEG_DEP_TIME  object
 15  BR_ARVL_DATE       object
 16  BR_ARVL_TIME       object
 17  SF_LOAD_DATE       object
 18  SF_LOAD_TIME       object
dtypes: datetime64[ns](4), int64(3), object(12)
memory usage: 965.6+ MB

In [23]:
df.describe()

C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:448: UserWarning:
Lux detects that attributes ['SCHD_LEG_DEP_TMS', 'ACTL_LEG_DEP_TMS', 'BR_ARVL_TMS', 'SF_LOAD_TMS'] may be temporal.
To display visualizations for these attributes accurately, please convert temporal attributes to Datetime objects.
For example, you can convert a Year attribute (e.g., 1998, 1971, 1982) using pd.to_datetime by specifying the `format` as '%Y'.

Here is a starter template that you can use for converting the temporal fields:
	df['SCHD_LEG_DEP_TMS'] = pd.to_datetime(df['SCHD_LEG_DEP_TMS'], format='<replace-with-datetime-format>')
	df['ACTL_LEG_DEP_TMS'] = pd.to_datetime(df['ACTL_LEG_DEP_TMS'], format='<replace-with-datetime-format>')
	df['BR_ARVL_TMS'] = pd.to_datetime(df['BR_ARVL_TMS'], format='<replace-with-datetime-format>')
	df['SF_LOAD_TMS'] = pd.to_datetime(df['SF_LOAD_TMS'], format='<replace-with-datetime-format>')

See more at: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html
If SF_LOAD_TMS is not a temporal attribute, please use override Lux's automatically detected type:
	df.set_data_type({'SF_LOAD_TMS':'quantitative'})
C:\Users\gauta\anaconda3\Lib\site-packages\IPython\core\formatters.py:922: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
Please report the following issue on Github: https://github.com/lux-org/lux/issues

C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py:632: UserWarning:Traceback (most recent call last):
  File "C:\Users\gauta\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'Timestamp' and 'numpy.int64'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py", line 594, in _ipython_display_
    self.maintain_recs()
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py", line 436, in maintain_recs
    custom_action_collection = custom_actions(rec_df)
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\action\custom.py", line 76, in custom_actions
    recommendation = lux.config.actions[action_name].action(ldf)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\action\temporal.py", line 54, in temporal
    vlist = VisList(intent, ldf)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\vis\VisList.py", line 43, in __init__
    self.refresh_source(self._source)
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\vis\VisList.py", line 336, in refresh_source
    lux.config.executor.execute(self._collection, ldf, approx=approx)
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py", line 138, in execute
    PandasExecutor.execute_aggregate(vis, isFiltered=filter_executed)
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py", line 211, in execute_aggregate
    vis._vis_data = (vis.data.groupby(groupby_attr.attribute, dropna=False, history=False).count().reset_index().rename(columns={index_name: "Record"}))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\groupby\groupby.py", line 1741, in count
    ids, _, ngroups = self.grouper.group_info
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\properties.pyx", line 36, in pandas._libs.properties.CachedProperty.__get__
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\groupby\ops.py", line 873, in group_info
    comp_ids, obs_group_ids = self._get_compressed_codes()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\groupby\ops.py", line 897, in _get_compressed_codes
    return ping.codes, np.arange(len(ping.group_index), dtype=np.intp)
           ^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\groupby\grouper.py", line 671, in codes
    return self._codes_and_uniques[0]
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\properties.pyx", line 36, in pandas._libs.properties.CachedProperty.__get__
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\groupby\grouper.py", line 780, in _codes_and_uniques
    codes, uniques = algorithms.factorize(  # type: ignore[assignment]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\algorithms.py", line 787, in factorize
    uniques, codes = safe_sort(
                     ^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\algorithms.py", line 1540, in safe_sort
    ordered = _sort_mixed(values)
              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\algorithms.py", line 1608, in _sort_mixed
    num_argsort = np.argsort(values[num_pos])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in argsort
  File "C:\Users\gauta\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py", line 1146, in argsort
    return _wrapfunc(a, 'argsort', axis=axis, kind=kind, order=order)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'Timestamp' and 'numpy.int64'

,FLIGHTNUMBER,SCHD_LEG_DEP_TMS,ACTL_LEG_DEP_TMS,INTERNATIONAL,BR_ARVL_TMS,COUNT_BAGS,SF_LOAD_TMS
count,6.661559e+06,6661559,6651293,6.661559e+06,6661559,6.661559e+06,6661559
mean,1.520230e+03,2023-07-15 09:25:57.021220864,2023-07-15 09:39:21.161412096,2.429287e-01,2023-07-15 07:00:56.745906432,1.607596e+00,2023-09-26 17:04:53.492980480
min,2.000000e+00,2023-05-25 00:15:00,2023-05-25 00:28:00,0.000000e+00,2023-05-24 08:18:00,1.000000e+00,2023-09-26 17:04:53.493000
25%,8.330000e+02,2023-06-19 14:46:00,2023-06-19 14:45:00,0.000000e+00,2023-06-19 12:18:00,1.000000e+00,2023-09-26 17:04:53.492999936
50%,1.524000e+03,2023-07-15 11:21:00,2023-07-15 12:02:00,0.000000e+00,2023-07-15 09:14:00,1.000000e+00,2023-09-26 17:04:53.492999936
75%,2.243000e+03,2023-08-09 13:35:00,2023-08-09 14:12:00,0.000000e+00,2023-08-09 11:34:00,2.000000e+00,2023-09-26 17:04:53.492999936
max,2.998000e+03,2023-09-05 23:55:00,2023-09-06 12:42:00,1.000000e+00,2023-09-06 01:23:00,2.200000e+01,2023-09-26 17:04:53.493000
std,8.379639e+02,NaN,NaN,4.288524e-01,NaN,1.085336e+00,NaN

In [24]:
#SQL Query to print number of records
query = """
SELECT COUNT(*)
FROM LOCAL_DATABASE.ORAAUE.UNT_BAGS;
"""
cur.execute(query)
n = cur.fetchone()
print("Number of records :", n[0])

Number of records : 6661559

In [25]:
#SQL to print data range
query = """
SELECT MIN(CAST(SCHD_LEG_DEP_TMS AS DATE)), MAX(CAST(SCHD_LEG_DEP_TMS AS DATE))
FROM LOCAL_DATABASE.ORAAUE.UNT_BAGS
"""
cur.execute(query)
date = cur.fetchone()

#Unpack tuple to print the date range
if date is not None:
    min_date, max_date = date
    print("Data available : \nFrom Date:", min_date)
    print("To Date:", max_date)
else:
    print("No data found")

Data available :
From Date: 2023-05-25
To Date: 2023-09-05

### Identify null values

In [26]:
null_values=df.isna()

In [27]:
df_null= df[df.isna().any(axis=1)]

In [28]:
df_null

C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:548: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:548: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:567: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:548: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py:567: UserWarning:Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
C:\Users\gauta\anaconda3\Lib\site-packages\IPython\core\formatters.py:922: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
Please report the following issue on Github: https://github.com/lux-org/lux/issues

C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py:632: UserWarning:Traceback (most recent call last):
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py", line 581, in _ipython_display_
    self.maintain_metadata()
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py", line 146, in maintain_metadata
    self.compute_metadata()
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\core\frame.py", line 126, in compute_metadata
    lux.config.executor.compute_dataset_metadata(self)
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py", line 448, in compute_dataset_metadata
    self.compute_data_type(ldf)
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\executor\PandasExecutor.py", line 506, in compute_data_type
    elif check_if_id_like(ldf, attr):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\lux\utils\utils.py", line 104, in check_if_id_like
    diff = series.diff()
           ^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\series.py", line 2870, in diff
    result = algorithms.diff(self._values, periods)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gauta\anaconda3\Lib\site-packages\pandas\core\algorithms.py", line 1454, in diff
    out_arr[res_indexer] = op(arr[res_indexer], arr[lag_indexer])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for -: 'datetime.time' and 'datetime.time'

,FLIGHTNUMBER,STATION,DESTINATION,SCHD_LEG_DEP_TMS,ACTL_LEG_DEP_TMS,INTERNATIONAL,FLEETTYPE,BODYTYPE,BR_ARVL_TMS,COUNT_BAGS,SF_LOAD_TMS,SCHD_LEG_DEP_DATE,SCHD_LEG_DEP_TIME,ACTL_LEG_DEP_DATE,ACTL_LEG_DEP_TIME,BR_ARVL_DATE,BR_ARVL_TIME,SF_LOAD_DATE,SF_LOAD_TIME
306,1691,ORD,EWR,2023-07-20 16:55:00,NaT,0,737,NARROWBODY,2023-07-20 13:54:00,1,2023-09-26 17:04:53.493,2023-07-20,16:55:00,NaN,NaN,2023-07-20,13:54:00,2023-09-26,17:04:53.493000
1051,2985,ORD,LGA,2023-07-09 10:20:00,NaT,0,737,NARROWBODY,2023-07-09 08:45:00,1,2023-09-26 17:04:53.493,2023-07-09,10:20:00,NaN,NaN,2023-07-09,08:45:00,2023-09-26,17:04:53.493000
2323,1850,ORD,RDU,2023-07-22 20:05:00,NaT,0,319,NARROWBODY,2023-07-22 19:14:00,3,2023-09-26 17:04:53.493,2023-07-22,20:05:00,NaN,NaN,2023-07-22,19:14:00,2023-09-26,17:04:53.493000
2633,1780,ORD,LGA,2023-08-23 13:18:00,NaT,0,319,NARROWBODY,2023-08-23 10:41:00,1,2023-09-26 17:04:53.493,2023-08-23,13:18:00,NaN,NaN,2023-08-23,10:41:00,2023-09-26,17:04:53.493000
3103,98,ORD,LHR,2023-08-23 20:46:00,NaT,1,787,WIDEBODY,2023-08-23 18:47:00,4,2023-09-26 17:04:53.493,2023-08-23,20:46:00,NaN,NaN,2023-08-23,18:47:00,2023-09-26,17:04:53.493000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6659487,2541,MIA,IAH,2023-08-17 20:37:00,NaT,0,737,NARROWBODY,2023-08-17 18:49:00,1,2023-09-26 17:04:53.493,2023-08-17,20:37:00,NaN,NaN,2023-08-17,18:49:00,2023-09-26,17:04:53.493000
6660443,995,MIA,GRU,2023-06-20 23:01:00,NaT,1,777,WIDEBODY,2023-06-20 19:34:00,3,2023-09-26 17:04:53.493,2023-06-20,23:01:00,NaN,NaN,2023-06-20,19:34:00,2023-09-26,17:04:53.493000
6661314,1921,MIA,TPA,2023-07-16 20:53:00,NaT,0,319,NARROWBODY,2023-07-16 21:05:00,1,2023-09-26 17:04:53.493,2023-07-16,20:53:00,NaN,NaN,2023-07-16,21:05:00,2023-09-26,17:04:53.493000
6661473,2702,MIA,YUL,2023-08-17 19:33:00,NaT,1,319,NARROWBODY,2023-08-17 17:26:00,1,2023-09-26 17:04:53.493,2023-08-17,19:33:00,NaN,NaN,2023-08-17,17:26:00,2023-09-26,17:04:53.493000
6661528,1530,MIA,LGA,2023-06-17 17:59:00,NaT,0,737,NARROWBODY,2023-06-17 15:59:00,1,2023-09-26 17:04:53.493,2023-06-17,17:59:00,NaN,NaN,2023-06-17,15:59:00,2023-09-26,17:04:53.493000

In [42]:
#Identifying Connecting flights

query = """
WITH UNIQUE_COMBI AS (
  SELECT DISTINCT FLIGHTNUMBER, STATION, DESTINATION
  FROM LOCAL_DATABASE.ORAAUE.UNT_BAGS
  GROUP BY FLIGHTNUMBER, STATION, DESTINATION
)
SELECT UC1.FLIGHTNUMBER, UC1.STATION AS STATION1, UC1.DESTINATION AS DESTINATION1,
       UC2.STATION AS STATION2, UC2.DESTINATION AS DESTINATION2
FROM UNIQUE_COMBI UC1
INNER JOIN UNIQUE_COMBI UC2 ON UC1.FLIGHTNUMBER = UC2.FLIGHTNUMBER
WHERE (UC1.STATION = UC2.DESTINATION)
ORDER BY UC1.FLIGHTNUMBER;
"""
cur.execute(query)
results = cur.fetchall()

In [44]:
column_names = [desc[0] for desc in cur.description]

In [45]:
df_connectingflights=pd.DataFrame(results, columns=column_names)

In [48]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None) 

print(df_connectingflights)

    FLIGHTNUMBER STATION1 DESTINATION1 STATION2 DESTINATION2
0            148      PHX          SNA      LAX          PHX
1            223      LAX          MCO      DFW          LAX
2            225      DFW          ONT      ORD          DFW
3            294      LAX          RDU      DFW          LAX
4            327      LAX          MIA      MIA          LAX
5            327      MIA          LAX      LAX          MIA
6            357      ORD          LGA      MIA          ORD
7            362      MIA          AUS      LAX          MIA
8            468      DFW          MSY      ORD          DFW
9            616      CLT          DCA      MIA          CLT
10           813      DFW          EWR      LAX          DFW
11           973      DFW          TUL      MIA          DFW
12          1058      MIA          ORD      ORD          MIA
13          1058      ORD          MIA      MIA          ORD
14          1265      DFW          PHL      LAX          DFW
15          1303      LAX          CLT      CLT          LAX
16          1303      CLT          LAX      LAX          CLT
17          1321      DFW          LAX      LAX          DFW
18          1321      LAX          DFW      DFW          LAX
19          1321      LAX          AUS      DFW          LAX
20          1348      LAX          DFW      DFW          LAX
21          1348      DFW          MFE      LAX          DFW
22          1348      DFW          LAX      LAX          DFW
23          1434      DFW          YVR      MIA          DFW
24          1437      CLT          TPA      DFW          CLT
25          1454      DFW          XNA      CLT          DFW
26          1463      DFW          LIT      ORD          DFW
27          1467      DFW          PVR      MIA          DFW
28          1467      DFW          SDF      MIA          DFW
29          1659      PHX          DFW      DFW          PHX
30          1659      DFW          PHX      PHX          DFW
31          1711      LAX          DFW      DFW          LAX
32          1711      DFW          LAX      LAX          DFW
33          1935      CLT          MIA      MIA          CLT
34          1935      CLT          RSW      MIA          CLT
35          1935      MIA          CLT      CLT          MIA
36          1959      LAX          MIA      MIA          LAX
37          1959      MIA          LAX      LAX          MIA
38          1966      CLT          LAX      LAX          CLT
39          1966      LAX          CLT      CLT          LAX
40          1974      DFW          LAX      LAX          DFW
41          1974      LAX          DFW      DFW          LAX
42          1980      LAX          DFW      DFW          LAX
43          1980      DFW          LAX      LAX          DFW
44          1987      LAX          ORD      ORD          LAX
45          1987      ORD          LAX      LAX          ORD
46          1991      MIA          LAX      LAX          MIA
47          1991      LAX          MIA      MIA          LAX
48          2002      LAX          ORD      ORD          LAX
49          2002      ORD          LAX      LAX          ORD
50          2019      CLT          LAX      LAX          CLT
51          2019      LAX          CLT      CLT          LAX
52          2062      PHX          ONT      DFW          PHX
53          2113      CLT          LAX      LAX          CLT
54          2113      LAX          CLT      CLT          LAX
55          2204      LAX          DFW      DFW          LAX
56          2204      DFW          LAX      LAX          DFW
57          2245      CLT          PHX      PHX          CLT
58          2245      PHX          CLT      CLT          PHX
59          2249      ORD          PHX      PHX          ORD
60          2249      PHX          ORD      ORD          PHX
61          2374      DFW          DTW      ORD          DFW
62          2416      ORD          JAX      LAX          ORD
63          2571      DFW          PHX      PHX          DFW
64          2571      PHX          DFW      DFW          PHX
65          2616      ORD          PDX      PHX          ORD
66          2813      DFW          SJO      ORD          DFW
67          2813      DFW          MIA      ORD          DFW
68          2838      PHX          SAN      ORD          PHX
69          2891      CLT          CMH      ORD          CLT
70          2906      CLT          GGT      MIA          CLT
71          2921      CLT          MYR      ORD          CLT
72          2939      LAX          ORD      DFW          LAX
73          2967      DFW          LAX      LAX          DFW
74          2967      LAX          DFW      DFW          LAX
75          2976      CLT          DAB      ORD          CLT
76          2980      LAX          ORD      ORD          LAX
77          2980      ORD          LAX      LAX          ORD

### Correlation Matrix

In [35]:
numerical_df = df.select_dtypes(include=[np.number])
corr_pearson_df=numerical_df.corr()
corr_pearson_df

Button(description='Toggle Pandas/Lux', layout=Layout(top='5px', width='140px'), style=ButtonStyle())

Output()

In [ ]:
cur.close()
conn.close()

In [18]:
#EDA with Pandas profiling
import pandas
from ydata_profiling import ProfileReport
pandasprofiling_report = ProfileReport(df, title="Pandas Profiling Report")
profile.to_file("UNT_BAGS_EDA_pandas_profiling.html")

ModuleNotFoundError: No module named 'ydata_profiling'